demo0/demo1/booktest/urls.py
from django.conf.urls import url,include
from . import views


app_name='booktest'
urlpatterns=[
    url(r'^$',views.index,name='indexes'),
    url(r'^list/$',views.Listview.as_view(),name='list'),
    # url(r'^list/$',views.list,name='list'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^deletehero/(\d+)/$',views.deletehero,name='deletehero'),
    url(r'^deletebook/(\d+)/$',views.deletebook,name='deletebook'),
    url(r'^addhero/(\d+)/$',views.addhero,name='addhero'),
    url(r'^addimg/$',views.Addimg.as_view(),name='addimg')
]

demo0/demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
import time
tt=str(int(time.time()*1000000))[6:16]
# print(tt)
# #在项目根路由下方引入应用路由配置文件
urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('booktest.urls',namespace='booktest')),
]

demo0/demo1/booktest/models.py
from django.db import models

class Ads(models.Model):
    title=models.CharField(max_length=20)
    img=models.ImageField(upload_to="static/img/")
    def __str__(self):
        return self.title

class HeroInfoManage(models.Manager):
    def addhero(self,_name,_content,_book,_gender):
        hero=HeroInfo()
        hero.name = _name
        hero.content = _content
        hero.book = _book
        hero.gender = _gender
        hero.save()
# Create your models here.
class Bookinfo(models.Model):
    title=models.CharField(max_length=20)
    pub_date=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

class HeroInfo(models.Model):
    name=models.CharField(max_length=20)
    gender=models.CharField(max_length=5,choices=(("man","男"),("woman","女")))
    # gender=models.BooleanField(default=True)
    content=models.CharField(max_length=100)
    book=models.ForeignKey(Bookinfo,on_delete=models.CASCADE)
    objects=HeroInfoManage()

#1对多
class User(models.Model):
    name=models.CharField(max_length=20)

class Account(models.Model):
    telephone=models.CharField(max_length=20)
    name=models.ForeignKey(User,on_delete=models.CASCADE)
#1对1
class Onestep(models.Model):
    name=models.CharField(max_length=20)
class Telephone(models.Model):
    phone=models.CharField(max_length=20)
    name=models.OneToOneField(Onestep,on_delete=models.CASCADE)
#多对多
class Host(models.Model):
    host=models.CharField(max_length=20)
class Application(models.Model):
    app=models.CharField(max_length=20)
    name=models.ManyToManyField(Host)

demo0/demo1/booktest/views.py
from django.shortcuts import render,redirect,reverse
from django.template import loader
# Create your views here.
from django.http import HttpResponse
from .models import Bookinfo,HeroInfo,HeroInfoManage,Ads
from django.views.generic import View,ListView


class Addimg(View):
    def get(self,request):
        # return  HttpResponse('打开上传页面')
        return render(request,"booktest/addimg.html")
    def post(self,request):
        ads=Ads()
        ads.title=request.POST.get('title')
        ads.img=request.FILES['addimg']
        ads.save()
        return  HttpResponse('上传成功')

#自定义视图函数   绑定路由
def index(request):
    ads=Ads.objects.all()
    return render(request,"booktest/indexes.html",{"username":"yyx",'ads':ads})

class Listview(ListView):
    model = Bookinfo
    template_name = "booktest/list.html"
    context_object_name = "books"
    def queryset(self):
        return Bookinfo.objects.all()
#返回渲染的结果
def list(request):
    books = Bookinfo.objects.all()
    return render(request,"booktest/list.html",{"books":books})

def detail(request,id):
    book = Bookinfo.objects.get(pk=id)
    return render(request,"booktest/result.html",{"book":book})
#重定向  两次请求  redirect 解决重定向问题  reverse解决页面跳转问题

def deletehero(request,id):
    hero=HeroInfo.objects.get(pk=id)
    bookid=hero.book.id
    hero.delete()
    return redirect(reverse("booktest:detail",args=(bookid,)))
def deletebook(request,id):
    book=Bookinfo.objects.get(pk=id)
    book.delete()
    return  redirect(reverse("booktest:list"))
def addhero(request,id):
    # book
    book=Bookinfo.objects.get(pk=id)
    if request.method=='GET':
        return render(request,"booktest/addhero.html",{'book':book})
    elif request.method=='POST':
        name=request.POST.get("username")
        content=request.POST.get("content")
        gender= request.POST.get("gender")
        HeroInfo.object.addhero(name,content,book,gender)

        return redirect(reverse("booktest:detail",args=(id,)))















    # temp1 = loader.get_template("booktest/result.html")
    # print(id)
    # result = temp1.render({'book':book})
    # return HttpResponse(result)
    # return HttpResponse("这是一个%s详情页 <a href='/'>跳转到首页</a>"%(id,))








# def ooo(request):
#     return HttpResponse('https://blog.csdn.net/u012069883/article/details/82378295')

# def myview(request):
#     return HttpResponse("这是一个自定义路由")
#
# def youview(request):
#     return HttpResponse("这是你的自定义路由")

demo0/demo1/templates/booktest/addimg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">

    <h2>添加图片</h2>
    <form enctype="multipart/form-data" class="form-horizontal" action="{% url 'booktest:addimg' %}" method="post">
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">图片描述</label>
            <div class="col-sm-6">
                <input type="text" name="title" class="form-control" id="title" placeholder="请输入图片描述">
            </div>
        </div>
        <div class="form-group">
            <label for="addimg" class="col-sm-2 control-label">添加图片</label>
            <div class="col-sm-6">
                <input type="file" name="addimg" class="form-control" id="addimg" >
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button type="submit" class="btn btn-default">添加</button>
            </div>
        </div>
    </form>
</div>
<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</body>
</html>

demo0/demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <p>显示详情</p>
    <a class="btn btn-info" href="{% url 'booktest:index' %}">回到首页</a>
    <a class="btn btn-info"  href="{% url 'booktest:list' %}">回到列表页</a>
    <h3>当前书籍为：{{book.title}}</h3>
    {% if book.heroinfo_set.count %}
        <h3>拥有角色</h3>
        <ul>
            {% for hero in book.heroinfo_set.all %}
            <li>{{hero.name}} -- 技能:{{ hero.content}}</li>
            <a class="btn btn-warning" href="{% url 'booktest:deletehero' hero.id %}">删除英雄</a>
            {% endfor %}
        </ul>
    {% else %}
        <h3>没有角色</h3>
    {% endif %}
    <a class="btn btn-success" href="{% url 'booktest:addhero' book.id %}">添加英雄</a>
<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
</body>
</html>

demo0/demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/main.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/main.js"></script>
</head>
<body>
<h1>首页</h1>
<p>当前用户：<span class="username">{{ username }}</span></p>
<!--<img src="/static/img/bg-login.png" alt="">-->
{# <a href="/list/">跳转列表页</a> #}
<a href="{% url 'booktest:list' %}">跳转列表页</a>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        {% for a in ads %}
        {% if forloop.counter == 1 %}
        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
        {% else %}
        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}"></li>
        {% endif %}
        {% endfor %}


        <!--<li data-target="#carousel-example-generic" data-slide-to="2"></li>-->
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        {% for a in ads %}
        {% if forloop.counter == 1 %}
        <div class="item active">
            <div align="center">
                <img src="/{{ a.img }}" alt="...">
            </div>
            <div class="carousel-caption">
                {{ a.title }}
            </div>
        </div>
        {% else %}
        <div class="item">
            <div align="center">
                <img src="/{{ a.img }}" alt="...">
            </div>
            <div class="carousel-caption">
                 {{ a.title }}
            </div>
        </div>
        {% endif %}
        {% endfor %}

    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>


</body>
</html>