demo0/demo6/apps/blog/urls.py
from . import views
from django.conf.urls import url
app_name="blog"
urlpatterns=[
    url(r'^$', views.blog, name='blog'),
    url(r'^single/(\d+)/$',views.Single.as_view(),name='single'),
    url(r'^addarticle/$',views.Addartical.as_view(),name='addrical'),
    url(r'^archives/(\d+)/(\d+)/$',views.Archives.as_view(),name='archives'),
    url(r'^cateart/(\d+)/$',views.Cateart.as_view(),name='cateart'),
    url(r'^tagart/(\d+)/$',views.Tagart.as_view(),name='tagart'),
    url(r'^login/$',views.login,name='login'),
    url(r'^regist/$',views.regist,name='regist'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^verify/',views.verify,name='verify'),
    url(r'^checkuser/$',views.checkuser,name='checkuser'),

]

demo0/demo6/apps/comment/urls.py
from django.conf.urls import url
from . import views
app_name="comment"
urlpatterns=[
    url(r'^comment/(\d+)/$',views.Allcommment.as_view(),name='comment')
]

demo0/demo6/demo6/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.views.static import serve
import xadmin
from .settings import MEDIA_ROOT
urlpatterns = [
    # path('admin/', admin.site.urls),
    url('xadmin/',xadmin.site.urls),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':MEDIA_ROOT}),
    url('',include('blog.urls', namespace='blog')),
    url('',include('comment.urls',namespace='comment')),
    url(r'ueditor/',include('DjangoUeditor.urls')),
    url('search/',include('haystack.urls')),

]

demo0/demo6/apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from DjangoUeditor.models import UEditorField
# Create your models here.
class Myuser(User):
    telephone=models.IntegerField(default=110)
    type=models.IntegerField(default=0)

class Ads(models.Model):
    img=models.ImageField(upload_to="ads")
    title=models.CharField(max_length=20)
    index=models.IntegerField()
    def __str__(self):
        return self.title

class Category(models.Model):
    title=models.CharField(max_length=20)
    def __str__(self):
        return self.title
class Tag(models.Model):
    title=models.CharField(max_length=20)
    def __str__(self):
        return self.title
class Artical(models.Model):
    title=models.CharField(max_length=20)
    createtime=models.DateTimeField(auto_now_add=True)
    updatetime=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    tag=models.ManyToManyField(Tag)
    view=models.IntegerField(default=0)
    author=models.ForeignKey(Myuser,on_delete=models.CASCADE)
    body=UEditorField(imagePath="articalimg/",width="100%")
    # def __str__(self):
    #     return self.author,self.tag

demo0/demo6/apps/comment/models.py
from django.db import models
from blog.models import Artical
# Create your models here.
class Comment(models.Model):
    artical=models.ForeignKey(Artical,on_delete=True)
    author=models.CharField(max_length=20)
    create_time=models.DateTimeField(auto_now_add=True)
    email=models.EmailField(blank=True,null=True)
    url=models.URLField(blank=True,null=True,default="http://www.baidu.com")
    body=models.TextField()

demo0/demo6/apps/blog/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Ads, Tag, Artical, Category, Myuser
from django.views import View
from .form import FormArtical, FormComment, LoginForm, RegistForm
from django.core.paginator import Paginator, Page
# Create your views here.
from django.contrib.auth import login as loi, logout as lot, authenticate
import random,io
from PIL import Image,ImageDraw,ImageFont
from django.http import HttpResponse,JsonResponse
from django.core.cache import cache
from django.core.mail import send_mail
from django.conf import settings
from django.views.decorators.cache import cache_page

# def checklogin(fun):
#     def checklog(request,*args):
#         if request.user and request.user.is_authenticated:
#             return redirect(reverse("blog:blog"))
#         else:
#             return redirect(reverse("blog:blog"))
#     return checklog
# 图片验证码功能
def verify(request):
# 定义变量， 用于画面的背景色、 宽、 高
    bgcolor = (random.randrange(20, 100),
               random.randrange(20, 100),
               random.randrange(20, 100))
    width = 100
    heigth = 35
# 创建画面对象
    im = Image.new('RGB', (width, heigth), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
# 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, heigth))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
# 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    cache.set("verify",rand_str)
    # 构造字体对象
    font = ImageFont.truetype('Arvo-Regular.ttf', 23)
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
# 释放画笔
    del draw
    request.session['verifycode'] = rand_str
    f = io.BytesIO()
    im.save(f, 'png')
    # 将内存中的图片数据返回给客户端， MIME类型为图片png
    return HttpResponse(f.getvalue(), 'image/png')
#当账户名不对时提示
def checkuser(request):
    if request.method == "GET":
        name = request.GET.get("name")
        qs = Myuser.objects.filter(username=name)
        user = qs.first()
        if user:
            return JsonResponse({"state":1})
        else:
            return JsonResponse({"state":0,'errorinfo':"用户名不存在"})
def logout(request):
    lot(request)
    return redirect(reverse("blog:blog"))
def regist(request):
    form = LoginForm()
    rgf = RegistForm()
    if request.method == 'GET':
        return render(request, "blog/login.html", locals())
    elif request.method == "POST":
        rgf = RegistForm(request.POST)
        if rgf.is_valid():
            user = rgf.save(commit=False)
            user.set_password(rgf.cleaned_data["password"])
            user.save()
            OOlist=["yyxyanyuxiang@163.com"]
            try:
                send_mail("python测试邮件","这是一封Python给你发的邮件",settings.EMAIL_HOST_USER,OOlist)
            except Exception as e:
                print(e)
            return redirect(reverse("blog:login"))
        else:
            return render(request, 'blog/login.html', {'erros': '注册失败'}, locals())
def login(request):
    form = LoginForm()
    rgf = RegistForm()
    if request.method == 'GET':
        return render(request, "blog/login.html", locals())
    elif request.method == 'POST':
        # 表单类自建
        verifydode=request.POST.get('verify')
        if not verifydode== cache.get("verify"):
            return HttpResponse("验证码错误")
        lgf = LoginForm(request.POST)
        print(dir(lgf))
        if lgf.is_valid():
            username = lgf.cleaned_data["username"]
            password = lgf.cleaned_data["password"]
            islogin = False
            user = authenticate(request, username=username, password=password)
            if user:
                loi(request, user)
                islogin = True
                return redirect(reverse("blog:blog"))
            else:
                return render(request, "blog/login.html", {'erros': '登录失败'}, locals())
# 分页类的实现
def getpage(request, object_list, per_num):
    pagenum = request.GET.get("page")
    pagenum = 1 if not pagenum else pagenum
    pagenum = int(pagenum)
    left_has_more = False
    right_has_more = False
    # #如果小于三就是显示...
    if pagenum > 3:
        left_has_more = True
    if (pagenum + 2) < Paginator(object_list, per_num).num_pages:
        right_has_more = True
    page = Paginator(object_list, per_num).get_page(pagenum)
    return page, left_has_more, right_has_more


@cache_page(60)
def blog(request):
    ads = Ads.objects.all()
    art = Artical.objects.all()
    username = request.user
    # art=[]
    # for i in range(pagenum-2,pagenum+3):
    #     if i>0 and i<Paginator(art,1).num_pages:
    #         art.append(i)
    page, left_has_more, right_has_more = getpage(request, art, 1)
    return render(request, "blog/indexes.html", locals())

class Single(View):
    def get(self, request, id):
        username = request.user
        art = Artical.objects.get(pk=id)
        art.view += 1
        # art.save()
        com = FormComment()
        return render(request, "blog/single.html", locals())
    def post(self, request, id):
        at = get_object_or_404(Artical, pk=id)
        print(at)
        art = FormComment(request.POST)
        com = art.save(commit=False)
        com.artical = at
        com.save()
        return redirect(reverse("blog:single", args=(at.id,)))
# 通过年月得到不同文章
class Archives(View):
    def get(self, request, year, month):
        ads = Ads.objects.all()
        article = Artical.objects.filter(createtime__year=year, createtime__month=month)
        page, left_has_more, right_has_more = getpage(request, article, 1)
        return render(request, "blog/indexes.html", locals())
    def post(self, request):
        pass
# 通过不同的分类得到不同的文章
class Cateart(View):
    def get(self, request, id):
        ads = Ads.objects.all()
        article = Artical.objects.filter(category=id)
        page, left_has_more, right_has_more = getpage(request, article, 1)
        return render(request, "blog/indexes.html", locals())
    def post(self, request):
        pass
# 通过不同的标签得到不同的文章
class Tagart(View):
    def get(self, request, id):
        ads = Ads.objects.all()
        article = Artical.objects.filter(tag=id)
        page, left_has_more, right_has_more = getpage(request, article, 1)
        return render(request, "blog/indexes.html", locals())
    def post(self, request):
        pass
# 增加文章
class Addartical(View):
    def get(self, request):
        rgf = FormArtical()
        username = request.user
        return render(request, "blog/addartical.html", locals())
    def post(self, request):
        rgf = FormArtical(request.POST)
        if rgf.is_valid():
            art = rgf.save(commit=False)
            art.author = Myuser.objects.filter(username=request.user)[0]
            art.save()
            return redirect(reverse("blog:blog"))
        else:
          return render(request, 'blog/addartical.html', {'erros': '发布失败'}, locals())

demo0/demo6/templates/blog/addartical.html
{% extends "blog/base.html" %}
{% block title %}<title>编辑文章</title>{% endblock title %}
{% block body %}
<main class="col-md-8" >
    {{ rgf.media }}
<form action="{% url 'blog:addrical' %}" method="post" class="form-group">
    {% csrf_token %}
    {{ rgf }}

    <br>
    <div  class="col-md-4 col-md-offset-2" >
        <input type="submit" value="发布文章" class="form-control">
    </div >
</form>
</main>
{% endblock body %}

demo0/demo6/templates/blog/base.html
<!DOCTYPE html>
{% load my_func %}
{% load cache %}
<html>
<head>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">
    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
    {% block title %}
    <title>博客实战</title>
    {% endblock %}
</head>

<body>
<div id="site-header">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:blog' %}"><b>博客实战</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:blog' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                            {% if username and request.user.is_authenticated %}
                            <li class="cl-effect-11"><a href="{% url 'blog:addrical' %}" data-hover="发布博客">发布博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:logout' %}" data-hover="退出登陆" >退出登陆</a></li>
                            当前用户是{{ request.user }}
                            {% else %}
                                <li class="cl-effect-11"><a href="{% url 'blog:login' %}" data-hover="注册登陆" >注册登陆</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="/search/">
                            <input type="search" placeholder="搜索"  name="q" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </div>
</div>
<div class="content-body">
    <div class="row">
        <div class="container">
            {% block body %}
            {% endblock%}
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% getlatestaticles as latestaticles %}
                        {% for i in latestaticles %}
                        <li>
                            <a href="#">{{ i.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% gettimes as time %}
                        {% for i in time %}
                        <li>
                            <a href="{% url 'blog:archives' i.year i.month %}">{{ i.year }}年 {{ i.month }} 月</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% getallcategray as allcategray %}
                        {% for i in allcategray %}
                        <li>
                            <a href="{% url 'blog:cateart' i.id %}">{{ i.title }}({{ i.artical_set.count }})</a>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% getalltag as alltag %}
                        {% for i in alltag %}
                        <li>
                            <a href="{% url 'blog:tagart' i.id %}">{{ i.title }}</a>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>
<script src="/static/js/script.js"></script>
</body>
</html>

demo0/demo6/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load my_func %}
{% block title %}
<title>博客首页</title>
{% endblock %}
{% block body %}

<main class="col-md-8">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            {% for a in ads %}
            {% if forloop.counter == 1 %}
            <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0}}" class="active"></li>
            {% else %}
            <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0}}"></li>
            {% endif %}
            {% endfor %}
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            {% for a in ads %}
                {% if forloop.counter == 1 %}
                <div class="item active">
                    <img src="/media/{{ a.img }}" alt="...">
                    <div class="carousel-caption">
                        <h1>{{ a.title }}</h1>
                    </div>
                </div>
                {% else %}
                <div class="item">
                    <img src="/media/{{ a.img }}" alt="...">
                    <div class="carousel-caption">
                        <h1>{{ a.title }}</h1>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <br><br><br><br><br>

    {% for a in page.object_list  %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{% url 'blog:single' a.id  %}">{{ a.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ a.category.title }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{ a.createtime }}</time></a></span>
                <span class="post-author"><a href="#">{{ a.author }}</a></span>
                <span class="comments-link"><a href="#">{{ a.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ a.view }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ a.body | safe  }}
            <div class="read-more cl-effect-14">
                <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% endfor %}

    <div class="pagination col-md-11">
        <ul>
            {% if page.has_previous %}
            <li class="col-md-2"><a href="?page={{ page.previous_page_number }}">上一页</a></li>
            {% endif %}
            {% if left_has_more %}
                <li class="col-md-1"><a href="?page={{ page.number |add:-3 }}">...</a></li>
            {% endif %}
            {% for i in page.paginator.page_range %}
                {% if i == page.number|add:-2 %}
                    <li  class=" col-md-1"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% if i == page.number|add:-1 %}
                    <li  class=" col-md-1"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% if i == page.number|add:+1 %}
                    <li  class=" col-md-1"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% if i == page.number|add:+2 %}
                    <li  class=" col-md-1"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% if i == page.number %}
                    <li  class="current col-md-1"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if right_has_more %}
                <li class="col-md-1"><a href="?page={{ page.number|add:+3 }}">...</a></li>
                {% if page.has_next %}

                <li class="col-md-2"><a href="?page={{ page.next_page_number }}">下一页</a></li>
                {% endif %}
            {% endif %}
        </ul>
    </div>
</main>
{% endblock %}

demo0/demo6/templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab"
                                                  data-toggle="tab">登录</a></li>
        <li role="presentation" ><a href="#regist" aria-controls="regist" role="tab" data-toggle="tab">注册</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane" id="regist">
            <p>{{ erros }}</p>
            <form class="form-horizonial" action="{% url 'blog:regist' %}" method="post">
                {% csrf_token %}
                {{ rgf }}
                <span>邮箱注册：</span><input type="email" id="email" name="email">
                <input type="submit" value="注册">
            </form>
        </div>
        <div role="tabpanel" class="tab-pane active" id="login">
            <p>{{ erros }}</p>
            <form class="form-horizonial" action="{% url 'blog:login' %}" method="post">
                {% csrf_token %}
                <div class="col-md-11">
                {{ form.username  }}
                    </div>
                <div id="cuo" class="col-md-1" hidden><img style="height: 30px;width: 30px" src="/static/img/dui.PNG" alt=""></div>
                <div id="dui" class="col-md-1" hidden><img style="height: 30px;width: 30px" src="/static/img/cuo.PNG" alt=""></div>
                <div class="col-md-11">
                {{ form.password }}
                    </div>
                <div class="col-md-1"></div>
                <br><br><br><br><br>
                <div>
                    <label for="verify">验证码</label>
                    <img id="btn_img" src="/verify" alt=""><input id="verify" type="text" name="verify">
                </div>
                <input type="submit" value="登录">
            </form>
        </div>
    </div>
</div>


<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
<script>
    $(function () {
        $('#btn_img').click(function () {
            $(this).attr('src','/verify/?t='+new Date().getTime())
        })
        $("#username").blur(function(){
        console.log("输入了用户名",$(this).val());
            $.ajax({
                url:"{% url 'blog:checkuser' %}",
                "type":"get",
                "data":{
                "name":$(this).val()
                },
                success:function(data){
                    if(data.state == 0)
                    {
                        $("#cuo").show(1)
                        $("#dui").hide()
                        // alert( data.errorinfo )

                    }
                    else{

                        $("#dui").show(1)
                        $("#cuo").hide()
                    }
                }
            })
        })
    })
</script>
</body>
</html>

demo0/demo6/templates/blog/single.html
{% extends 'blog/base.html' %}
{% block title %}
<title>博客详细</title>
{% endblock %}
{% block body %}
<main class="col-md-8">
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ art.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ art.category.title }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{ art.create_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ art.author }}</a></span>
                <span class="comments-link"><a href="#">{{ art.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ art.view }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ art.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <div class="comment-form">
        <h3>发表评论</h3>
        <div class="row" >
                <div class="col-md-4">
                    <label >名字：</label>
                    {{ com.author }}
                </div>
                <div class="col-md-4">
                    <label >邮箱：</label>
                    {{ com.email }}
                </div>
                <div class="col-md-4">
                    <label >网址：</label>
                    {{ com.url }}
                </div>
                <div class="col-md-12">
                    <label >评论：</label>
                    {{ com.body }}
                    <button id="btn_commit" class="comment-btn">发表</button>
                </div>
            </div>


        <div class="comment-list-panel">
            <h3>评论列表，共 <span id="qwe">{{ art.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled" id="commentlist">
                {% for i in art.comment_set.all %}
                <li class="comment-item">
                    <span class="nickname" id="comauthor">{{ i.author }}</span>
                    <time class="submit-date" id="comtime" datetime="2012-11-09T23:15:57+00:00">{{ i.create_time }}</time>
                    <div class="text" >
                        {{ i.body }}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
            </div>
    </section>
</main>
<script>
    $(function () {
        $("#btn_commit").click(function () {
            $.ajax({
                url:"{% url 'comment:comment' art.id %}",
                type:"post",
                data:{
                    "csrfmiddlewaretoken":"{{csrf_token}}",
                    "author":$("#id_author").val(),
                    "email":$("#id_email").val(),
                    "url":$("#id_url").val(),
                    "body":$("#id_body").val()
                },
                success:function (data) {
                    console.log(data);
                    a=Number($('#qwe').text())
                    $('#qwe').text((a+1)+"")
                    $('#id_author').val("")
                    $('#id_body').val("")
                    $('#id_email').val("")
                    $('#commentlist').append('<li class="comment-item"><span class="nickname">'+data.author+'</span><time class="submit-date" datetime="2012-11-09T23:15:57+00:00">'+data.time+'</time><div class="text">'+data.body+'</div></li>');
                }
            })
        })
    })
</script>
{% endblock %}